Traceback (most recent call last):
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyvista
from dolfinx import plot

pyvista.set_jupyter_backend("panel")
pyvista.set_plot_theme("paraview")
pyvista.start_xvfb(wait=0.1)

cells, types, x = plot.vtk_mesh(V)
grid = pyvista.UnstructuredGrid(cells, types, x)
# Create plotter and pyvista grid
p = pyvista.Plotter()

p.add_mesh(grid, show_edges=True)
p.view_xy()
p.show_axes()
p.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m~/.local/lib/python3.10/site-packages/pyvista/jupyter/__init__.py:80[0m, in [0;36m_validate_jupyter_backend[0;34m(backend)[0m
[1;32m     79[0m [38;5;28;01mtry[39;00m:
[0;32m---> 80[0m     [38;5;28;01mimport[39;00m [38;5;21;01mpanel[39;00m
[1;32m     81[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:  [38;5;66;03m# pragma: no cover[39;00m

[0;31mModuleNotFoundError[0m: No module named 'panel'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[5], line 4[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpyvista[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdolfinx[39;00m [38;5;28;01mimport[39;00m plot
[0;32m----> 4[0m [43mpyvista[49m[38;5;241;43m.[39;49m[43mset_jupyter_backend[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mpanel[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      5[0m pyvista[38;5;241m.[39mset_plot_theme([38;5;124m"[39m[38;5;124mparaview[39m[38;5;124m"[39m)
[1;32m      6[0m pyvista[38;5;241m.[39mstart_xvfb(wait[38;5;241m=[39m[38;5;241m0.1[39m)

File [0;32m~/.local/lib/python3.10/site-packages/pyvista/jupyter/__init__.py:206[0m, in [0;36mset_jupyter_backend[0;34m(backend)[0m
[1;32m    113[0m [38;5;28;01mdef[39;00m [38;5;21mset_jupyter_backend[39m(backend):
[1;32m    114[0m [38;5;250m    [39m[38;5;124;03m"""Set the plotting backend for a jupyter notebook.[39;00m
[1;32m    115[0m 
[1;32m    116[0m [38;5;124;03m    Parameters[39;00m
[0;32m   (...)[0m
[1;32m    204[0m 
[1;32m    205[0m [38;5;124;03m    """[39;00m
[0;32m--> 206[0m     pyvista[38;5;241m.[39mglobal_theme[38;5;241m.[39m_jupyter_backend [38;5;241m=[39m [43m_validate_jupyter_backend[49m[43m([49m[43mbackend[49m[43m)[49m
[1;32m    207[0m     [38;5;28;01mif[39;00m backend [38;5;129;01min[39;00m [[38;5;124m'[39m[38;5;124mserver[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mclient[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mtrame[39m[38;5;124m'[39m]:
[1;32m    208[0m         [38;5;66;03m# Launch the trame server[39;00m
[1;32m    209[0m         [38;5;28;01mfrom[39;00m [38;5;21;01mpyvista[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtrame[39;00m[38;5;21;01m.[39;00m[38;5;21;01mjupyter[39;00m [38;5;28;01mimport[39;00m elegantly_launch

File [0;32m~/.local/lib/python3.10/site-packages/pyvista/jupyter/__init__.py:82[0m, in [0;36m_validate_jupyter_backend[0;34m(backend)[0m
[1;32m     80[0m     [38;5;28;01mimport[39;00m [38;5;21;01mpanel[39;00m
[1;32m     81[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:  [38;5;66;03m# pragma: no cover[39;00m
[0;32m---> 82[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m([38;5;124m'[39m[38;5;124mPlease install `panel` to use this feature.[39m[38;5;124m'[39m)
[1;32m     83[0m panel[38;5;241m.[39mextension([38;5;124m'[39m[38;5;124mvtk[39m[38;5;124m'[39m)
[1;32m     84[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m pyvista[38;5;241m.[39mBUILDING_GALLERY:

[0;31mImportError[0m: Please install `panel` to use this feature.

