Traceback (most recent call last):
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
u_topology, u_cell_types, u_geometry = plot.vtk_mesh(VT)
u_grid = pyvista.UnstructuredGrid(u_topology, u_cell_types, u_geometry)
u_3D = np.zeros((u_geometry.shape[0], 3))
u_3D[:, :2] = u.x.array.reshape(-1, 2)
u_grid.point_data["Displacement"] = u_3D
u_grid.set_active_vectors("Displacement")
warped = u_grid.warp_by_vector("Displacement", factor=10)

plotter = pyvista.Plotter()
plotter.add_mesh(warped, show_edges=True)
plotter.view_xy()
plotter.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[6], line 4[0m
[1;32m      2[0m u_grid [38;5;241m=[39m pyvista[38;5;241m.[39mUnstructuredGrid(u_topology, u_cell_types, u_geometry)
[1;32m      3[0m u_3D [38;5;241m=[39m np[38;5;241m.[39mzeros((u_geometry[38;5;241m.[39mshape[[38;5;241m0[39m], [38;5;241m3[39m))
[0;32m----> 4[0m [43mu_3D[49m[43m[[49m[43m:[49m[43m,[49m[43m [49m[43m:[49m[38;5;241;43m2[39;49m[43m][49m [38;5;241m=[39m u[38;5;241m.[39mx[38;5;241m.[39marray[38;5;241m.[39mreshape([38;5;241m-[39m[38;5;241m1[39m, [38;5;241m2[39m)
[1;32m      5[0m u_grid[38;5;241m.[39mpoint_data[[38;5;124m"[39m[38;5;124mDisplacement[39m[38;5;124m"[39m] [38;5;241m=[39m u_3D
[1;32m      6[0m u_grid[38;5;241m.[39mset_active_vectors([38;5;124m"[39m[38;5;124mDisplacement[39m[38;5;124m"[39m)

[0;31mValueError[0m: could not broadcast input array from shape (451,2) into shape (126,2)

