Traceback (most recent call last):
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tdim = domain.topology.dim
cell_markers = mark_entities(
    domain, tdim, {1: inclusions, 2: lambda x: np.logical_not(inclusions(x))}
)

k = create_piecewise_constant_field(domain, cell_markers, {1: 1.0, 2: 10.0})
xdofs = k.function_space().tabulate_dofs_coordinates()
plt.scatter(*xdofs, k.vector.array)
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 7[0m
[1;32m      2[0m cell_markers [38;5;241m=[39m mark_entities(
[1;32m      3[0m     domain, tdim, {[38;5;241m1[39m: inclusions, [38;5;241m2[39m: [38;5;28;01mlambda[39;00m x: np[38;5;241m.[39mlogical_not(inclusions(x))}
[1;32m      4[0m )
[1;32m      6[0m k [38;5;241m=[39m create_piecewise_constant_field(domain, cell_markers, {[38;5;241m1[39m: [38;5;241m1.0[39m, [38;5;241m2[39m: [38;5;241m10.0[39m})
[0;32m----> 7[0m xdofs [38;5;241m=[39m [43mk[49m[38;5;241;43m.[39;49m[43mfunction_space[49m[43m([49m[43m)[49m[38;5;241m.[39mtabulate_dofs_coordinates()
[1;32m      8[0m plt[38;5;241m.[39mscatter([38;5;241m*[39mxdofs, k[38;5;241m.[39mvector[38;5;241m.[39marray)
[1;32m      9[0m plt[38;5;241m.[39mshow()

[0;31mTypeError[0m: 'FunctionSpaceBase' object is not callable

