Traceback (most recent call last):
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plot_quad_rule("xiao_gimbutas", color="C0")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m [43mplot_quad_rule[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mxiao_gimbutas[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mcolor[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mC0[39;49m[38;5;124;43m"[39;49m[43m)[49m

Cell [0;32mIn[1], line 17[0m, in [0;36mplot_quad_rule[0;34m(name, color)[0m
[1;32m     16[0m [38;5;28;01mdef[39;00m [38;5;21mplot_quad_rule[39m(name, color[38;5;241m=[39m[38;5;124m"[39m[38;5;124mC0[39m[38;5;124m"[39m):
[0;32m---> 17[0m     rule, degs, cell_types [38;5;241m=[39m [43mquad_rules[49m[43m[[49m[43mname[49m[43m][49m
[1;32m     18[0m     [38;5;28;01mfor[39;00m deg [38;5;129;01min[39;00m degs:
[1;32m     19[0m         plt[38;5;241m.[39mfigure()

[0;31mKeyError[0m: 'xiao_gimbutas'

