Traceback (most recent call last):
  File "/home/bleyerj/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/.local/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bleyerj/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/bleyerj/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tao.setObjective(problem.f)
tao.setGradient(problem.F)
tao.setHessian(problem.J, problem.A)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 2[0m
[1;32m      1[0m tao[38;5;241m.[39msetObjective(problem[38;5;241m.[39mf)
[0;32m----> 2[0m [43mtao[49m[38;5;241;43m.[39;49m[43msetGradient[49m[43m([49m[43mproblem[49m[38;5;241;43m.[39;49m[43mF[49m[43m)[49m
[1;32m      3[0m tao[38;5;241m.[39msetHessian(problem[38;5;241m.[39mJ, problem[38;5;241m.[39mA)

File [0;32mpetsc4py/PETSc/TAO.pyx:198[0m, in [0;36mpetsc4py.PETSc.TAO.setGradient[0;34m()[0m

[0;31mTypeError[0m: setGradient() takes at least 2 positional arguments (1 given)

