Traceback (most recent call last):
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/bleyerj/.local/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyvista

pyvista.set_jupyter_backend("static")

# Grid for the mesh
tdim = domain.topology.dim
mesh_topology, mesh_cell_types, mesh_geometry = plot.vtk_mesh(domain, tdim)
mesh_grid = pyvista.UnstructuredGrid(mesh_topology, mesh_cell_types, mesh_geometry)

# Grid for functions (2nd order elements)
u_topology, u_cell_types, u_geometry = plot.vtk_mesh(V)
u_grid = pyvista.UnstructuredGrid(u_topology, u_cell_types, u_geometry)

# Plot the first 3 eigenmodes
pl = pyvista.Plotter(shape=(2, 3))
for i in range(N_eig):
    pl.subplot(i)
    eigenmode = f"eigenmode_{i:02}"
    pl.add_text(
        f"Eigenmode {i+1}",
        font_size=12,
    )
    eigen_vector = eigvec_r[i]
    u_grid[eigenmode] = eigen_vector.x.array.reshape(
        u_geometry.shape[0], V.dofmap.index_map_bs
    )
    pl.add_mesh(mesh_grid, style="wireframe")
    pl.add_mesh(u_grid.warp_by_vector(eigenmode, factor=0.02), show_scalar_bar=False)
    pl.zoom_camera("tight")
    pl.view_isometric()
pl.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 17[0m
[1;32m     15[0m pl [38;5;241m=[39m pyvista[38;5;241m.[39mPlotter(shape[38;5;241m=[39m([38;5;241m2[39m, [38;5;241m3[39m))
[1;32m     16[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(N_eig):
[0;32m---> 17[0m     [43mpl[49m[38;5;241;43m.[39;49m[43msubplot[49m[43m([49m[43mi[49m[43m)[49m
[1;32m     18[0m     eigenmode [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124meigenmode_[39m[38;5;132;01m{[39;00mi[38;5;132;01m:[39;00m[38;5;124m02[39m[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m     19[0m     pl[38;5;241m.[39madd_text(
[1;32m     20[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mEigenmode [39m[38;5;132;01m{[39;00mi[38;5;241m+[39m[38;5;241m1[39m[38;5;132;01m}[39;00m[38;5;124m"[39m,
[1;32m     21[0m         font_size[38;5;241m=[39m[38;5;241m12[39m,
[1;32m     22[0m     )

File [0;32m~/.local/lib/python3.10/site-packages/pyvista/plotting/plotter.py:948[0m, in [0;36mBasePlotter.subplot[0;34m(self, index_row, index_column)[0m
[1;32m    922[0m [38;5;28;01mdef[39;00m [38;5;21msubplot[39m([38;5;28mself[39m, index_row, index_column[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m    923[0m [38;5;250m    [39m[38;5;124;03m"""Set the active subplot.[39;00m
[1;32m    924[0m 
[1;32m    925[0m [38;5;124;03m    Parameters[39;00m
[0;32m   (...)[0m
[1;32m    946[0m 
[1;32m    947[0m [38;5;124;03m    """[39;00m
[0;32m--> 948[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrenderers[49m[38;5;241;43m.[39;49m[43mset_active_renderer[49m[43m([49m[43mindex_row[49m[43m,[49m[43m [49m[43mindex_column[49m[43m)[49m

File [0;32m~/.local/lib/python3.10/site-packages/pyvista/plotting/renderers.py:368[0m, in [0;36mRenderers.set_active_renderer[0;34m(self, index_row, index_column)[0m
[1;32m    366[0m [38;5;28;01mif[39;00m index_row [38;5;241m<[39m [38;5;241m0[39m [38;5;129;01mor[39;00m index_row [38;5;241m>[39m[38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mshape[[38;5;241m0[39m]:
[1;32m    367[0m     [38;5;28;01mraise[39;00m [38;5;167;01mIndexError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mRow index is out of range ([39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mshape[[38;5;241m0[39m][38;5;132;01m}[39;00m[38;5;124m)[39m[38;5;124m'[39m)
[0;32m--> 368[0m [38;5;28;01mif[39;00m [43mindex_column[49m[43m [49m[38;5;241;43m<[39;49m[43m [49m[38;5;241;43m0[39;49m [38;5;129;01mor[39;00m index_column [38;5;241m>[39m[38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mshape[[38;5;241m1[39m]:
[1;32m    369[0m     [38;5;28;01mraise[39;00m [38;5;167;01mIndexError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mColumn index is out of range ([39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39mshape[[38;5;241m1[39m][38;5;132;01m}[39;00m[38;5;124m)[39m[38;5;124m'[39m)
[1;32m    370[0m [38;5;28mself[39m[38;5;241m.[39m_active_index [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mloc_to_index((index_row, index_column))

[0;31mTypeError[0m: '<' not supported between instances of 'NoneType' and 'int'

